my %london_tube_colors = (
  'Bakerloo'           => "#987020",
  'Central'            => "#F00",
  'Circle'             => "#F5F500",
  'District'           => "#0A0",
  'DLR'                => "#008887",
  'East London'        => "#FC0",
  'Hammersmith & City' => "#FBB",
  'Jubilee'            => "#CCC",
  'Metropolitan'       => "#A0A",
  'Northern'           => "#000",
  'Overground'         => "#E86A10",
  'Piccadilly'         => "#0000f0",
  'Victoria'           => "#50b8FF",
  'Waterloo & City'    => "#8F8",
  'Crossrail'          => "#3FF",
);
